/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, 2)


PB_BIND(Discovery, Discovery, 2)


PB_BIND(Confirmation, Confirmation, AUTO)





